version: '3.8'

services:
  postgres:
    container_name: pg16_pgadmin
    image: postgres:16
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin123
      POSTGRES_DB: unodb
    ports:
      - "5435:5432"
    volumes:
      - pg_data_pgadmin:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data_pgadmin:
    driver: local