services:
  db:
    container_name: "pg16_uno"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgreSQLR0ck%"
      # No PGDATA environment variable here - let PostgreSQL use default
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    user: postgres  # Explicitly set the user to postgres

volumes:
  pg_data:
    driver: local
