"""
DTOManagerProtocol: Protocol for schema/DTO manager services.
"""

from typing import Protocol, Any


class DTOManagerProtocol(Protocol):
    def add_schema_config(self, name: str, config: Any) -> None: ...
    def create_schema(self, schema_name: str, model: type[Any]) -> Any: ...
    def create_all_schemas(self, model: type[Any]) -> dict[str, Any]: ...
    def get_schema(self, schema_name: str) -> Any | None: ...
    def register_standard_configs(self) -> None: ...
    def create_standard_schemas(self, model: type[Any]) -> dict[str, Any]: ...
